baseURL = 'http://localhost'
#baseURL = 'https://www.etlcpp.com/hugo/'
languageCode = 'en-gb'
title = 'Documentation for the ETL'
theme = "etl_theme"

[module]
  [[module.mounts]]
    source = "../docs"
    target = "content/docs"

disablePathToLower = true

enableGitInfo = true

[markup]
  [markup.highlight]
    style = "perldoc"

[markup.goldmark.renderer]
  unsafe = false

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'logo.png'

  # (Optional, default 'favicon.png') Set the path to a favicon for the site.
  # If the favicon is in /static/custom.svg, then the path would be 'custom.svg'.
  BookFavicon = 'favicon.png'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'docs'

  # (Optional, default none) Set template for commit link for the page. Requires enableGitInfo.
  # When set enabled 'Last Modified' and a link to the commit in the footer of the page.
  # Param is executed as template using .Site, .Page and .GitInfo as context.
  BookLastChangeLink = 'https://github.com/ETLCPP/etl/commit/{{ .GitInfo.Hash }}'

  # (Optional, default none) Set template for edit page link.
  # When set enabled 'Edit this page' link in the footer of the page.
  # Param is executed as template using .Site, .Page and .Path as context.
  BookEditLink = 'https://github.com/ETLCPP/etl/edit/main/docs/{{ .Path }}'

  # (Optional, default 'January 2, 2006') Configure the date format used on the pages
  # - In git information
  # - In blog 
  # Set to international date format.
  # https://gohugo.io/functions/time/format/
  BookDateFormat = '2006-01-02'

  # (Optional) Search configuration
  BookSearchConfig = { "indexed" = true }

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = true
