baseURL = 'http://localhost/'
#baseURL = 'https://www.etlcpp.com/hugo/'
languageCode = 'en-gb'
title = 'Embedded Template Library'
theme = 'hextra'

[markup]
  [markup.highlight]
    noClasses = false   # Must be false to use external CSS
    style = "github"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.parser.attribute]
    block = true

[module]
  [[module.mounts]]
    source = "../docs"
    target = "content/docs"

[params]
  contentDir = "content/docs"
  
  [params.theme]
    customCSS = ["css/custom.css"]

  [params.page]
    width = "wide"

  [params.navbar]
    displayTitle = true
    [params.navbar.logo]
      path = "images/logo.png"
      link = "/"

  [params.search]
    enable = true
    
  [params.sidebar]
    # This stops the sidebar from "drilling down" into H2/H3 headers
    levels = 1 
    # Ensure these are also set to prevent auto-expansion
    defaultOpen = false
    autoCollapse = true

[[menus.main]]
  name = "Home"
  pageRef = "/docs"
  weight = 1

[[menus.main]]
name = "About"
url = "/about/"
weight = 999

[[menus.main]]
name = "Blog"
url = "/blog/"
weight = 3