baseURL = 'http://localhost/'
#baseURL = 'https://www.etlcpp.com/hugo/'
languageCode = 'en-gb'
title = 'Embedded Template Library'
theme = 'hextra'

[markup]
  [markup.highlight]
    style = "github"

  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.mounts]]
    source = "../docs"
    target = "content/docs"

[params]
  [params.theme]
    customCSS = ["css/custom.css"]

  contentDir = "content/docs"

  [params.navbar]
    displayTitle = true
    [params.navbar.logo]
      path = "images/logo.png"
      link = "/"