version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2022
configuration:
- Debug MSVC C++14
- Debug MSVC C++14 - No STL
- Debug MSVC C++17
- Debug MSVC C++17 - No STL
- Debug MSVC C++20
- Debug MSVC C++20 - No STL
clone_folder: c:\projects\etl
install:
- cmd: git submodule update --init --recursive
build:
  project: test/vs2022/etl.vcxproj
  verbosity: minimal

  