version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration:
- Debug
- Debug - No STL
- Debug MSVC - No STL - Built-ins
- Debug MSVC - Force C++03
clone_folder: c:\projects\etl
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: git clone https://github.com/unittest-cpp/unittest-cpp.git c:\projects\unittest-cpp
build:
  project: test/vs2019/etl.vcxproj
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://hooks.slack.com/services/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
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
  