//***************************************************************************
// THIS FILE HAS BEEN AUTO GENERATED. DO NOT EDIT THIS FILE.
//***************************************************************************

/*[[[cog
import cog
cog.outl("")
cog.outl("  //***************************************************************************")
cog.outl("  // For %s types." % int(NTypes))
cog.outl("  //***************************************************************************")
cog.outl("  template <typename T0,")
for n in range(1, int(NTypes) - 1):
    cog.outl("            typename T%s = void," % n)
cog.outl("            typename T%s = void>" %(int(NTypes) - 1))
cog.outl("  struct type_select")
cog.outl("  {")
cog.outl("  public:")
cog.outl("")
cog.outl("    template <size_t Id>")
cog.outl("    struct select")
cog.outl("    {")
cog.outl("      typedef typename etl::conditional<Id == 0, T0,")
for n in range(1, int(NTypes)) :
    cog.outl("              typename etl::conditional<Id == %s, T%s," % (n, n))
cog.outl("              etl::null_type<0> >")
cog.out("              ")
for n in range(1, int(NTypes)) :
    cog.out("::type>")
    if n % 8 == 0:
        cog.outl("")
        cog.out("              ")
cog.outl("::type type;")
cog.outl("");
cog.outl("      ETL_STATIC_ASSERT(Id < %s, \"Invalid Id\");" % int(NTypes));
cog.outl("    };")
cog.outl("  };")

for s in range(int(NTypes) - 1, 0, -1):
    cog.outl("")
    cog.outl("  //***************************************************************************")
    cog.outl("  // For %s types." % int(s))
    cog.outl("  //***************************************************************************")
    cog.out("  template <")
    for n in range(0, s - 1):
        cog.outl("typename T%s, " % n)
        cog.out("            ")
    cog.outl("typename T%s>" % (s - 1))
    cog.out("  struct type_select<")
    for n in range(0, s - 1):
        cog.out("T%s, " % n)
    cog.outl("T%s>" % (s - 1))
    cog.outl("  {")
    cog.outl("  public:")
    cog.outl("    template <size_t Id>")
    cog.outl("    struct select")
    cog.outl("    {")
    cog.outl("      typedef typename etl::conditional<Id == 0, T0,")
    for n in range(1, s) :
        cog.outl("              typename etl::conditional<Id == %s, T%s," % (n, n))
    cog.outl("              etl::null_type<0> >")
    cog.out("              ")
    for n in range(1, s) :
        cog.out("::type>")
        if n % 8 == 0:
          cog.outl("")
          cog.out("              ")
    cog.outl("::type type;")
    cog.outl("");
    cog.outl("      ETL_STATIC_ASSERT(Id < %s, \"Invalid Id\");" % s);
    cog.outl("    };")
    cog.outl("  };")
]]]*/
/*[[[end]]]*/
