.PHONY: clean All

All:
	@echo "----------Building project:[ ETL - Debug ]----------"
	@$(MAKE) -f  "ETL.mk" && $(MAKE) -f  "ETL.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ ETL - Debug ]----------"
	@$(MAKE) -f  "ETL.mk" clean
