name: clang-tidy

on:
  push:
    branches: [ master, development, pull-request/* ]
    paths:
      - '.github/workflows/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'BUILD.bazel'
      - 'MODULE.bazel*'
      - 'meson.build'
      - 'meson_options.txt'
      - 'subprojects/**'
      - '.devcontainer/**'
  pull_request:
    branches: [ master, development, pull-request/* ]
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'BUILD.bazel'
      - 'MODULE.bazel*'
      - 'meson.build'
      - 'meson_options.txt'
      - 'subprojects/**'
      - '.devcontainer/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang clang-tidy
          clang --version
          clang-tidy --version
          run-clang-tidy --version || true

      - name: Run clang-tidy
        run: |
          test/run-clang-tidy.sh
