name: Deploy documentation via SFTP

on:
  push:
    branches:
      - feature/sftp-documentation-on-push-to-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./hugo

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Install and set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Build the static site
      - name: Build Hugo Site
        run: hugo --cleanDestinationDir --minify --baseURL "https://www.etlcpp.com/hugo/"

      - name: Verify key hash
        run: printf '%s' "$KEY" | sha256sum
        env:
          KEY: ${{ secrets.DOCS_BDEPLOY_KEY }}

      # Securely upload the files via SFTP
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.DOCS_SSH_SERVER }}
          username: ${{ secrets.DOCS_SSH_USER }}
          ssh_private_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          port: ${{ secrets.DOCS_SSH_PORT }}
          local_path: ./hugo/public/*
          remote_path: ${{ secrets.DOCS_DEST_DIR }}
          