name: Deploy documentation to www.etlcpp.com

on:
  push:
    branches:
      - master

    workflow_dispatch:

jobs:
  build_deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.1'
          extended: true

      - name: Build
        working-directory: hugo
        run: hugo --minify --cleanDestinationDir --baseURL "https://www.etlcpp.com/"

      # Deploys the site via the deploy script in the ci directory
      - name: Deploy
        run: source $GITHUB_WORKSPACE/scripts/deploy_documentation.sh
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DOCS_BDEPLOY_KEY }}
          SSH_USERNAME: ${{ secrets.DOCS_SSH_USER }}
          SERVER_ADDRESS: ${{ secrets.DOCS_SSH_SERVER }}
          SERVER_DESTINATION: ${{ secrets.DOCS_DEST_DIR }}
          SSH_PORT: ${{ secrets.DOCS_SSH_PORT }}
