name: gcc-c++23-powerpc
on:
  push:
    branches: [ master, development, pull-request/* ]
  pull_request:
    branches: [ master, development, pull-request/* ]
    types: [opened, synchronize, reopened]

jobs:

  build-gcc-cpp23-linux-no-stl-powerpc:
    name: GCC C++23 Linux - No STL - powerpc
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t etl-powerpc -f .devcontainer/powerpc/Dockerfile .

    - name: Build and run tests
      run: |
        docker run --rm --user root -v ${{ github.workspace }}:/workspaces/etl etl-powerpc bash -c "\
          cmake -DBUILD_TESTS=ON -DNO_STL=ON -DETL_USE_TYPE_TRAITS_BUILTINS=OFF -DETL_USER_DEFINED_TYPE_TRAITS=OFF -DETL_FORCE_TEST_CPP03_IMPLEMENTATION=OFF \
           -DETL_CXX_STANDARD=23 -DCMAKE_TOOLCHAIN_FILE=.devcontainer/powerpc/toolchain-powerpc.cmake \
           -DEXTRA_TESTING_FLAGS=-v \
           ./ && \
          cmake --build . -- -j \$(getconf _NPROCESSORS_ONLN) && \
          ctest -V"
