name: posix
on:
  push:
#branches: [ master, development, pull-request/* ]
  pull_request:
    branches: [ master, pull-request/* ]
  workflow_dispatch:

jobs:
  posix:
    name: Posix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cpp-ver: ["03", 11, 14, 17, 20, 23]
        no-stl: [ON, OFF]
        force-03: [ON, OFF]
        compiler: [GCC, LLVM]
        os: [ubuntu-24.04, macos-13]
        exclude:
          - cpp-ver: 03
            force-03: ON
          - compiler: GCC
            os: macos-14
        include:
          - tests: YES
          - cpp-ver: "03"
            tests: NO
          - compiler: GCC
            cc: gcc
            cxx: g++
          - compiler: LLVM
            cc: clang
            cxx: clang++
    env:
      ASAN_OPTIONS: alloc_dealloc_mismatch=0,detect_leaks=0
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      CXX_VER: ${{ matrix.cpp-ver }}
      FORCE_03: ${{ matrix.force-03 }}
      NO_STL: ${{ matrix.no-stl }}

    steps:
    - uses: actions/checkout@v4

    - name: Versions
      run: |
        cmake --version
        ${CXX} --version
        make --version

    - name: Syntax check
      run: |
        mkdir syntax-check
        cd syntax-check
        cmake ../test/syntax_check/c++${CXX_VER} \
          -DNO_STL=${NO_STL} \
          -DETL_USE_TYPE_TRAITS_BUILTINS=OFF \
          -DETL_USER_DEFINED_TYPE_TRAITS=OFF \
          -DETL_FORCE_TEST_CPP03_IMPLEMENTATION=${FORCE_03}
        make -j $(getconf _NPROCESSORS_ONLN)

    - name: Configure
      if: ${{ matrix.tests == 'YES' }}
      run: |
        mkdir build
        cd build
        cmake .. \
          -DBUILD_TESTS=YES \
          -DNO_STL=${NO_STL} \
          -DETL_USE_TYPE_TRAITS_BUILTINS=OFF \
          -DETL_USER_DEFINED_TYPE_TRAITS=OFF \
          -DETL_FORCE_TEST_CPP03_IMPLEMENTATION=${FORCE_03} \
          -DETL_CXX_STANDARD=${CXX_VER}

    - name: Build
      if: ${{ matrix.tests == 'YES' }}
      run: |
        cd build
        # getconf as portable solution via https://stackoverflow.com/a/64571679/6178613
        make -j $(getconf _NPROCESSORS_ONLN)
    
    - name: Run tests
      if: ${{ matrix.tests == 'YES' }}
      run: ./build/test/etl_tests
